### ISSUE TITLE
项目克隆下来 同步出问题

### ISSUE THREAD

**Issue by leok0ng** [zhouzhuo810/ZzImageBox#2]
Gradle sync failed: Connection refused: connect
Consult IDE log for more details (Help | Show Log)

我把distributionUrl改成本地的了还是不行
distributionUrl=file:///C:/Users/xyf/.gradle/wrapper/dists/gradle-2.14.1-all.zip
 是什么问题啊 大兄弟 @zhouzhuo810

**Comment by leok0ng** [comment]
能加下QQ嘛 我Q763467305

**Comment by zhouzhuo810** [comment]
应该是之前gradle.properties文件中设置了代理；新版本已经没有了
