### ISSUE TITLE
控件使用的问题

### ISSUE THREAD

**Issue by oksimple** [zhouzhuo810/ZzImageBox#3]
你这个控件相当于外部不能套用有外边距和内边距，否则图片就会变形拉伸，这个问题咋解决呢？

**Comment by oksimple** [comment]
我已经修复了这个问题。在imagview iv_pic外面套一层自定义的布局搞定

**Comment by chunmiao3032** [comment]
不知道是怎么回事，向控件中加载了几个图片后，报out of memory的错误了，是不是加载图片缩略图时没有对缩略图进行压缩呢？

**Comment by oksimple** [comment]
@chunmiao3032  你需要对图片用加载框架做处理不然，图片是有多大加载多大，内存要 爆

**Comment by chunmiao3032** [comment]
ok.收到，已经将图片压缩了，然后显示就没问题了，多谢哥们！

发自我的华为手机

-------- 原始邮件 --------
主题：Re: [zhouzhuo810/ZzImageBox] 控件使用的问题 (#3)
发件人：oksimple
收件人：zhouzhuo810/ZzImageBox
抄送：杨春苗 ,Mention


@chunmiao3032<https://github.com/chunmiao3032> 你需要对图片用加载框架做处理不然，图片是有多大加载多大，内存要 爆

―

**Comment by chunmiao3032** [comment]
最近发现，如果只用显示模式，添加两张图片后，会显示出六张，一份是重复的，而且还多一个空白的

发自我的华为手机

-------- 原始邮件 --------
主题：Re: [zhouzhuo810/ZzImageBox] 控件使用的问题 (#3)
发件人：oksimple
收件人：zhouzhuo810/ZzImageBox
抄送：杨春苗 ,Mention


@chunmiao3032<https://github.com/chunmiao3032> 你需要对图片用加载框架做处理不然，图片是有多大加载多大，内存要 爆

―

**Comment by oksimple** [comment]
@chunmiao3032  我没发现这个问题啊

**Comment by zhouzhuo810** [comment]
应该不会吧  是不是特殊原因导致重复添加了  可以贴出代码看看 或者提供demo
