### ISSUE TITLE
添加图片没有不显示缩略图问题

### ISSUE THREAD

**Issue by Mit0901** [zhouzhuo810/ZzImageBox#6]
我自己开发的软件，使用你的控件，在添加图片后无法显示缩略图，我找不出原因。
但是使用你的demo去添加同一张图片却可以显示缩略图。

**Comment by zhouzhuo810** [comment]
设置GlobalImageLoader，然后用Glide等框架来处理就好了呀。

**Comment by Mit0901** [comment]
谢谢，完美解决了
